plugin:
    name: 'eev.frontpage::lang.plugin.name'
    description: 'eev.frontpage::lang.plugin.description'
    author: 'Evgeny Epifanov'
    icon: icon-bars
    homepage: 'https://eecode.ru'
permissions:
    eev.widgets.manage-widgets:
        tab: 'eev.frontpage::lang.widgets'
        label: 'eev.frontpage::lang.manage-widgets'
navigation:
    frontpage:
        label: 'eev.frontpage::lang.plugin.name'
        url: eev/frontpage/widgetcontroller
        icon: icon-bars
        permissions:
            - eev.widgets.manage-widgets