title: 'eev.widgets::lang.widgets'
modelClass: EEV\Widgets\Models\Widget
list: $/eev/widgets/models/widget/columns.yaml
recordUrl: 'eev/widgets/widgetcontroller/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
