name: 'eev.frontpage::lang.widget'
form: $/eev/frontpage/models/widget/fields.yaml
modelClass: EEV\Frontpage\Models\Widget
defaultRedirect: eev/frontpage/widgetcontroller
create:
    title: 'eev.frontpage::lang.creating'
    redirect: 'eev/frontpage/widgetcontroller/update/:id'
    redirectClose: eev/frontpage/widgetcontroller
    flashSave: 'eev.frontpage::lang.saved'
update:
    title: 'eev.frontpage::lang.updating'
    redirect: eev/frontpage/widgetcontroller
    redirectClose: eev/frontpage/widgetcontroller
    flashSave: 'eev.frontpage::lang.saved'
